// Do not edit this file manually
import { parseBlockSchema } from "@typebot.io/forge";
import { nucleoQueryBlock } from "./index";

export const nucleoQueryBlockSchema = parseBlockSchema(nucleoQueryBlock);
